# Generated by Django 3.2 on 2021-04-26 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whitelist_domains', related_query_name='whitelist_domain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhiteList Domain',
                'verbose_name_plural': 'WhiteList Domains',
            },
        ),
        migrations.CreateModel(
            name='BlackListDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blacklist_domains', related_query_name='blacklist_domain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BlackList Domain',
                'verbose_name_plural': 'BlackList Domains',
            },
        ),
    ]
